In [64]:
#set-up
import json as json
import pandas as pd
import time

In [65]:
file_names = ['goodreads_reviews_dedup']

In [66]:
#my preprocessing
with open('goodreads_reviews_dedup.json', 'r') as f:
        lines = []
        for i in range(100):
            line = f.readline()
            if not line:
                break  # End of file reached
            lines.append(json.loads(line))

In [67]:
print(type(lines[1]))

<class 'dict'>

In [68]:
#convert dict to dataframe
reviews = pd.DataFrame(lines)
print(testing)

0     [Mind, blowingly, cool, ., Best, science, fict...
1     [This, is, a, special, book, ., It, started, s...
2     [I, have, n't, read, a, fun, mystery, book, in...
3     [Fun, ,, fast, paced, ,, and, disturbing, tale...
4     [A, fun, book, that, gives, you, a, sense, of,...
                            ...
95    [Just, heard, a, talk, by, Chip, which, was, v...
96    [The, Name, of, the, Rose, is, a, thrilling, D...
97    [An, extremely, well-written, account, of, the...
98    [*, *, spoiler, alert, *, *, An, interesting, ...
99    [This, is, a, book, that, every, entrepreneur,...
Name: review_text, Length: 100, dtype: object

In [69]:
# import libraries for NLP

import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('vader_lexicon')

[nltk_data] Downloading package punkt to /Users/Girl2/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /Users/Girl2/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /Users/Girl2/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

True

In [50]:
#tokenize text

##lower all for uniformity
reviews["review_text"] = reviews["review_text"].str.lower()

##tokenize
tokenized_reviews = reviews["review_text"].apply(word_tokenize)

##remove stopwords = come back to this
tokenized_reviews["review_text"] = [word for word in tokenized_reviews if word not in stopwords.words('english')]

##Lemmatize text (get root of word so there's not a billion variations of 'read')
###make this a function so it can be applied to the column using .apply
###actually make whole thing into function maybe
def my_lemmatizer(text):
    lemmatizer = WordNetLemmatizer()
    lemmatized_tokens = [lemmatizer.lemmatize(word) for word in text]
#lemmatized_tokens = [lemmatizer.lemmatize(word) for word in filtered_tokens]

#tokenized_reviews = tokenized_reviews["review_text"].apply(my_lemmatizer)

tokenized_reviews

0              [mind, blowingly, cool, ., best, science, fict...
1              [this, is, a, special, book, ., it, started, s...
2              [i, have, n't, read, a, fun, mystery, book, in...
3              [fun, ,, fast, paced, ,, and, disturbing, tale...
4              [a, fun, book, that, gives, you, a, sense, of,...
                                     ...
96             [the, name, of, the, rose, is, a, thrilling, d...
97             [an, extremely, well-written, account, of, the...
98             [*, *, spoiler, alert, *, *, an, interesting, ...
99             [this, is, a, book, that, every, entrepreneur,...
review_text    [[mind, blowingly, cool, ., best, science, fic...
Name: review_text, Length: 101, dtype: object

In [74]:
# initialize NLTK sentiment analyzer

analyzer = SentimentIntensityAnalyzer()

def get_sentiment(text):

    scores = analyzer.polarity_scores(text)
    #sentiment = 1 if scores['pos'] > 0 else 0
    
    # decide sentiment as positive, negative and neutral
    if scores['compound'] >= 0.05 :
        sentiment = "Positive"
 
    elif scores['compound'] <= - 0.05 :
        sentiment = "Negative"
 
    else :
        sentiment = "Neutral"

    return sentiment

In [75]:
#tokenized_reviews['sentiment'] = "testing"
#tokenized_reviews['sentiment'] = tokenized_reviews['review_text'].apply(get_sentiment)
reviews['sentiment'] = reviews["review_text"].apply(get_sentiment)

reviews

,user_id,book_id,review_id,rating,review_text,date_added,date_updated,read_at,started_at,n_votes,n_comments,sentiment
0,8842281e1d1347389f2ab93d60773d4d,24375664,5cd416f3efc3f944fce4ce2db2290d5e,5,Mind blowingly cool. Best science fiction I've...,Fri Aug 25 13:55:02 -0700 2017,Mon Oct 09 08:55:59 -0700 2017,Sat Oct 07 00:00:00 -0700 2017,Sat Aug 26 00:00:00 -0700 2017,16,0,Positive
1,8842281e1d1347389f2ab93d60773d4d,18245960,dfdbb7b0eb5a7e4c26d59a937e2e5feb,5,This is a special book. It started slow for ab...,Sun Jul 30 07:44:10 -0700 2017,Wed Aug 30 00:00:26 -0700 2017,Sat Aug 26 12:05:52 -0700 2017,Tue Aug 15 13:23:18 -0700 2017,28,1,Positive
2,8842281e1d1347389f2ab93d60773d4d,6392944,5e212a62bced17b4dbe41150e5bb9037,3,I haven't read a fun mystery book in a while a...,Mon Jul 24 02:48:17 -0700 2017,Sun Jul 30 09:28:03 -0700 2017,Tue Jul 25 00:00:00 -0700 2017,Mon Jul 24 00:00:00 -0700 2017,6,0,Positive
3,8842281e1d1347389f2ab93d60773d4d,22078596,fdd13cad0695656be99828cd75d6eb73,4,"Fun, fast paced, and disturbing tale of murder...",Mon Jul 24 02:33:09 -0700 2017,Sun Jul 30 10:23:54 -0700 2017,Sun Jul 30 15:42:05 -0700 2017,Tue Jul 25 00:00:00 -0700 2017,22,4,Positive
4,8842281e1d1347389f2ab93d60773d4d,6644782,bd0df91c9d918c0e433b9ab3a9a5c451,4,A fun book that gives you a sense of living in...,Mon Jul 24 02:28:14 -0700 2017,Thu Aug 24 00:07:20 -0700 2017,Sat Aug 05 00:00:00 -0700 2017,Sun Jul 30 00:00:00 -0700 2017,8,0,Positive
...,...,...,...,...,...,...,...,...,...,...,...,...
95,8842281e1d1347389f2ab93d60773d4d,612532,3dea47acbe98261b736694e0bcc95b1c,0,Just heard a talk by Chip which was very inspi...,Thu Sep 23 09:27:55 -0700 2010,Fri Sep 24 00:12:33 -0700 2010,,,2,4,Positive
96,8842281e1d1347389f2ab93d60773d4d,8694005,0e317947e1fd341f573192111bb2921d,3,The Name of the Rose is a thrilling Dan Brown-...,Wed Sep 08 01:22:27 -0700 2010,Wed Dec 14 12:30:43 -0800 2016,Mon Aug 10 00:00:00 -0700 2015,Mon Jul 20 00:00:00 -0700 2015,17,6,Positive
97,8842281e1d1347389f2ab93d60773d4d,8213519,1044128b0d6dea81a41b4107378931b2,5,An extremely well-written account of the 2008 ...,Thu Jul 08 07:33:27 -0700 2010,Wed Mar 22 11:46:45 -0700 2017,Thu Oct 14 00:00:00 -0700 2010,Mon Sep 06 00:00:00 -0700 2010,16,7,Negative
98,8842281e1d1347389f2ab93d60773d4d,7112495,0258b3c9a85cecb95f240e43a7642f60,4,** spoiler alert ** \n An interesting book in ...,Thu Jun 10 14:41:13 -0700 2010,Tue Aug 07 12:11:05 -0700 2012,Sat Aug 07 00:00:00 -0700 2010,Mon Jul 05 00:00:00 -0700 2010,7,3,Positive
99,8842281e1d1347389f2ab93d60773d4d,7518289,265c3e164075223139bb33ed37f19937,5,This is a book that every entrepreneur definit...,Fri May 14 13:11:51 -0700 2010,Thu Sep 22 14:31:47 -0700 2011,Sun Dec 12 00:00:00 -0800 2010,Sat Nov 27 00:00:00 -0800 2010,33,11,Positive

In [63]:
print(type(tokenized_reviews['review_text']))

<class 'list'>